# Generated by Django 2.2 on 2019-06-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_player_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='breed',
            new_name='color',
        ),
    ]
