# Generated by Django 2.2 on 2019-06-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190618_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('PURPLE', 'Purple'), ('BLACK', 'Black'), ('WHITE', 'White')], default='BLUE', max_length=10),
        ),
    ]
