# Generated by Django 2.2 on 2019-06-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190618_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='description',
        ),
        migrations.AddField(
            model_name='player',
            name='drink',
            field=models.CharField(choices=[('BEER', 'I crush brews'), ('WINE', "I love sippin' on some vino"), ('LIQUOR', 'Give me the hard stuff'), ('NONE', "Drinking isn't really my thing")], default='BEER', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(choices=[('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40+')], default='21', max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('PURPLE', 'Purple')], default='BLUE', max_length=10),
        ),
    ]
